version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres-container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
